config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :books
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_many :authors_books, dependent: :destroy
  has_many :books, through: :authors_books

  validates :first_name, :last_name, presence: true
end

app/models/authors_book.rb
# frozen_string_literal: true

class AuthorsBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user

  validates(
    :first_name,
    :last_name,
    :address,
    :city,
    :zip,
    :country,
    :phone,
    presence: true
  )

  validates_format_of :phone, with: Constants::PHONE_PATTERN, allow_blank: true
  validates :zip, numericality: { only_integer: true }, allow_blank: true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :authors_books, dependent: :destroy
  has_many :authors, through: :authors_books
  has_many :reviews, dependent: :destroy

  has_many :books_categories, dependent: :destroy
  has_many :categories, through: :books_categories

  has_many :order_items, dependent: :destroy

  has_many_attached :images

  validates :title, :description, :price, :year, presence: true

  validates :price, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100_000 }
end

app/models/books_category.rb
# frozen_string_literal: true

class BooksCategory < ApplicationRecord
  belongs_to :category
  belongs_to :book
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_and_belongs_to_many :books

  validates :name, presence: true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true

  validates :discount, inclusion: { in: 1..99 }
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates :number, :card_name, :expiration_date, :cvv, presence: true

  validates_format_of :expiration_date, with: Constants::CARD_DATE_PATTERN
  validates :number, numericality: { only_integer: true }, length: { is: Constants::CARD_NUMBER_LENGTH }
  validates :cvv, numericality: { only_integer: true }, length: { is: Constants::CARD_CVV_LENGTH }
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :nullify
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :books, through: :order_items
  has_one :coupon, dependent: :nullify
  belongs_to :delivery, optional: true
  belongs_to :user, optional: true

  enum status: %i[created in_progress in_delivery delivered canceled]
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum status: %i[unprocessed approved rejected]

  validates :rating, inclusion: { in: 1..5 }
  validates :body, :rating, presence: true
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :user

  validates(
    :first_name,
    :last_name,
    :address,
    :city,
    :zip,
    :country,
    :phone,
    presence: true
  )

  validates_format_of :phone, with: Constants::PHONE_PATTERN, allow_blank: true
  validates :zip, numericality: { only_integer: true }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :billing, dependent: :destroy
  has_one :shipping, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :credit_card, dependent: :destroy

  accepts_nested_attributes_for :billing
  accepts_nested_attributes_for :shipping
  accepts_nested_attributes_for :credit_card

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.provider = auth.provider
      user.uid = auth.uid
      user.skip_confirmation!
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :save_my_previous_url

  def index
    @book_count = Book.count
    @categories = Category.select(:id, :name)
    @order_param = params[:sort_by] || Constants::DEFAULT_BOOKS_ORDER

    result = BooksQuery.call(category: params[:category], sort_param: params[:sort_by]).page(params[:page]).per(Constants::BOOKS_PER_PAGE)
    @books = BookDecorator.decorate_collection(result)
  end

  def show
    @book = Book.find(params[:id]).decorate
    @reviews = ReviewDecorator.decorate_collection(Review.approved.where(book: @book.object))
    @back = session[:my_previous_url]
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @latest_books = BookDecorator.decorate_collection(BooksQuery.call(latest_books: nil))
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/home/_bestsellers.html.haml
%h3= t('home.best_sellers')
.row
  -@best_sellers.each do |book|
    .col-sm-6.col-md-3
      .general-thumb-wrap
        .thumbnail.general-thumbnail
          - if book.images.any?
            = image_tag(book.cover, class: 'img-shadow general-thumbnail-img')
          - else
            = image_tag('no_cover.jpg', class: 'img-shadow general-thumbnail-img')
          .thumb-hover
            .general-thumb-link-wrap
              %a.thumb-hover-link{href: book_path(book)}
                %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
              = link_to order_order_items_path(current_order, book_id: book, quantity: 1), method: :post, remote: true, class: 'thumb-hover-link add-to-cart', onclick: "addToCart()" do
                %i.fa.fa-shopping-cart.thumb-icon
      .mb-35
        .clearfix
          %p.pull-right.font-16.in-gold-500= number_to_currency(book.price)
          %p.title.mr-55= book.title
        %span.divider-sm
        %p.lead.small= book.authors_names

app/views/home/_carousel.html.haml
#slider.carousel.slide{'data-ride': "carousel"}
  %ol.carousel-indicators
    - @latest_books.each_with_index do |_book, index|
      -if index.zero?
        %li.active{'data-target': "#slider", 'data-slide-to': "#{index}"}
      -else
        %li{'data-target': "#slider", 'data-slide-to': "#{index}"}
  .carousel-inner{role: "listbox"}
    - @latest_books.each_with_index do |book, index|
      .item{ class: ('active' if index.zero?) }
        .row
          .col-sm-5
            .general-img-wrap
              - if book.images.any?
                = image_tag(book.cover, class: 'img-shadow general-thumbnail-img')
              - else
                = image_tag('no_cover.jpg', class: 'img-shadow general-thumbnail-img')
          .col-sm-7
            .mb-60
              %h1= book.title
              %p.lead= book.description
              %p.lead.small= book.authors_names

              .general-align
                = link_to t('home.buy_now'), order_order_items_path(current_order, book_id: book, quantity: 1), method: :post, class: 'btn btn-primary', onclick: "addToCart()"

  %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
    %span.icon-prev{'aria-hidden': "true"}
    %span.sr-only= t('home.previous')
  %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
    %span.icon-next{'aria-hidden': "true"}
    %span.sr-only= t('home.next')

app/views/home/index.html.haml
%main.container
  = render partial: 'carousel'

.container
  .jumbotron.text-center.mb-0
    %h2.h1= t('home.greeting')
    .mb-res-50
      %p= t('home.greeting_description')
    = link_to t('home.get_started'), books_path, class: 'button btn btn-default'

  .mb-35#bestsellers
    = render partial: 'bestsellers'